// source - https://bulbapedia.bulbagarden.net/wiki/Mega_Evolution
// TODO: support charizard x and y and mewtwo x and y

const megas = [
  'abomasnow',
  'absol',
  'aerodactyl',
  'aggron',
  'alakazam',
  'altaria',
  'ampharos',
  'audino',
  'banette',
  'beedrill',
  'blastoise',
  'blaziken',
  'camerupt',
  'charizard',
  'diancie',
  'gallade',
  'garchomp',
  'gardevoir',
  'gengar',
  'glalie',
  'gyarados',
  'heracross',
  'houndoom',
  'kangaskhan',
  'latias',
  'latios',
  'lopunny',
  'lucario',
  'manectric',
  'mawile',
  'medicham',
  'metagross',
  'mewtwo',
  'pidgeot',
  'pinsir',
  'rayquaza',
  'sableye',
  'salamence',
  'sceptile',
  'scizor',
  'sharpedo',
  'slowbro',
  'steelix',
  'swampert',
  'tyranitar',
  'venusaur',
]

export function canMega(pokemon: string): boolean {
  return megas.includes(pokemon.toLowerCase())
}
